// QA interactivo: navegación, formulario, lightbox y menú móvil. Uso: node scripts/qa.mjs
import { chromium } from 'playwright'
const URL = process.env.URL || 'http://localhost:3127/'
const T = '/tmp/csfb/qa-'
const b = await chromium.launch({ executablePath: '/usr/bin/google-chrome', args: ['--enable-unsafe-swiftshader', '--use-angle=swiftshader', '--ignore-gpu-blocklist'] })
const errors = []
const hook = (p, n) => { p.on('console', (m) => ['error', 'warning'].includes(m.type()) && errors.push(`${n} [${m.type()}] ${m.text()}`)); p.on('pageerror', (e) => errors.push(`${n} [pageerror] ${e.message}`)) }

let ctx = await b.newContext({ viewport: { width: 1440, height: 900 } })
let p = await ctx.newPage(); hook(p, 'desktop')
await p.goto(URL); await p.waitForTimeout(5000)
await p.click('nav[aria-label="Principal"] >> text=Admisión 2027')
await p.waitForTimeout(4000)
console.log('admision top tras clic:', await p.evaluate(() => Math.round(document.getElementById('admision').getBoundingClientRect().top)))
await p.evaluate(() => document.getElementById('form-admision').scrollIntoView({ block: 'start' }))
await p.waitForTimeout(1500)
await p.click('button[type="submit"]')
await p.waitForTimeout(500)
console.log('errores de validación visibles:', await p.locator('[id^="e-"]').count())
await p.screenshot({ path: T + 'form-errores.png' })
await p.fill('#apoderado', 'María Fernanda Quispe')
await p.fill('#telefono', '987 654 321')
await p.fill('#email', 'maria@correo.com')
await p.fill('#postulante', 'Lucía')
await p.selectOption('#grado', 'Primaria · 1.º grado')
await p.click('form label:has-text("Visita guiada")')
await p.check('input[name="acepto"]')
await p.click('button[type="submit"]')
await p.waitForTimeout(1800)
console.log('éxito:', await p.locator('text=¡Gracias, María!').count())
await p.screenshot({ path: T + 'form-ok.png' })
await p.evaluate(() => document.getElementById('vida').scrollIntoView())
await p.waitForTimeout(2000)
await p.click('button[aria-label="Ampliar foto: Nueva biblioteca"]')
await p.waitForTimeout(1200)
await p.screenshot({ path: T + 'lightbox.png' })
await p.keyboard.press('Escape')
await p.waitForTimeout(600)
console.log('lightbox cerrado:', (await p.locator('[role="dialog"]').count()) === 0)
// lectura del escudo
await p.evaluate(() => document.getElementById('identidad').scrollIntoView())
await p.waitForTimeout(1500)
await p.click('button[aria-label="SFB: Nuestro nombre"]')
await p.waitForTimeout(500)
await p.screenshot({ path: T + 'escudo.png' })
await ctx.close()

ctx = await b.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 })
p = await ctx.newPage(); hook(p, 'mobile')
await p.goto(URL); await p.waitForTimeout(4500)
await p.tap('button[aria-controls="menu-movil"]')
await p.waitForTimeout(1200)
await p.screenshot({ path: T + 'menu.png' })
await p.tap('#menu-movil >> text=Contacto')
await p.waitForTimeout(2500)
console.log('contacto top (móvil):', await p.evaluate(() => Math.round(document.getElementById('contacto').getBoundingClientRect().top)))
await ctx.close()
await b.close()
console.log(errors.length ? errors.join('\n') : 'consola: sin errores ni advertencias')
